### ISSUE TITLE
Access nested structures 

### ISSUE THREAD

**Issue by Asierisusi** [stlehmann/pyads#371] opened 2024-03-13 08:32 UTC
Lately, I've been working a lot with this library, and it's amazing. However, I've encountered several difficulties that I haven't been able to solve.

My test structure lis as follows:

**stPruebaEstruc**
fPrueba
bPrueba
iPrueba
Positions (Array [1..3] of ST_Position):
   |_ Positions[1]
   |  |_ ST_Position
   |     |_ X
   |     |_ Y
   |     |_ Z1
   |     |_ Z2
   |
   |_ Positions[2]
   |  |_ ST_Position
   |     |_ X
   |     |_ Y
   |     |_ Z1
   |     |_ Z2
   |
   |_ Positions[3]
      |_ ST_Position
         |_ X
         |_ Y
         |_ Z1
         |_ Z2

![NestedStructure](https://github.com/stlehmann/pyads/assets/84118769/b279c225-ebf6-478a-9990-8c8f392020e8)

Based on the documentation, to access a structure it's necessary to first define "structure_def." I've had issues reading pyads.PLCTYPE_UINT and including nested structures within this structure definition. That's why, as can be seen in the image, I need to manually define the array of structures "Posiciones" outside the definition of "ST_Prueba_structure_def."

By doing it this way, I generate an ads symbol that has the following structure.

![AdsSymbol](https://github.com/stlehmann/pyads/assets/84118769/415da76c-d8a6-40b7-b443-66207550152c)

The only particularity I've found when comparing it with an array of LREALs is the plc_type variable, which is generated for my array of structures.

I imagine there might be something I'm not understanding or interpreting correctly, but it would be very helpful to shed some light on this topic. Thank you very much, and I apologize if I haven't explained myself thoroughly.

**Comment by chrisbeardy** [comment] 2024-03-13 08:55
Hello, thanks for your question.

Firstly, you need to make sure that all structures in the PLC are marked with the attribute pack_mode = 1 (https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2529746059.html&id=).

Also as you may have noticed as you have implemented a workaround, nested structures don't really work smoothly. The workaround for this is noted in #308. At some point I hope to make this a better solution.

Closing issue as duplicate of #308

**Closed by chrisbeardy** 2024-03-13 08:55 UTC
