### ISSUE TITLE
How to access a Nested Structs?

### ISSUE THREAD

**Issue by fieryWaters** [stlehmann/pyads#350] opened 2023-04-28 02:17 UTC
Hi, the documentation does not cover nested custom datatypes. Is this supported?

For example, if I have:
TYPE TPoint : 
	STRUCT
		x : REAL;
		y : REAL;
	END_STRUCT
END_TYPE

TYPE ListOfPoints:
	STRUCT
		rampPoints : ARRAY [1..30] OF TPoint;
		rampSize : INT := 0;
	END_STRUCT
END_TYPE

In PyADS, I try: 

TPoint_def = (
         ("x", pyads.PLCTYPE_REAL, 1),
         ("y", pyads.PLCTYPE_REAL, 1)
     )

ListOfPoints_def=(
    ("rampPoints", TPoint_def, 30),
    ("rampSize", pyads.PLCTYPE_INT,1)
    )

test1 = plc.get_symbol("Main.test1", structure_def=ListOfPoints_def, array_size=1)

Is there a Pythonic way to do this or do I just need to avoid custom nested types? Thanks!

**Comment by chrisbeardy** [comment] 2023-04-28 09:11
hello, unfortunately this is not directly supported, but there is a workaround. please see #308. Hopefully support for this will be directly added to pyads at some point.

Please can you close this issue as it is a duplicate of #308, thanks. Any comments / additions, please add to #308.

**Comment by chrisbeardy** [comment] 2023-05-09 10:43
@stlehmann this can be closed, duplicate #308, thanks

**Closed** 2023-10-20 07:42 UTC
