### ISSUE TITLE
Compatibility Issue with adslib.so on 64-bit Raspberry Pi OS

### ISSUE THREAD

**Issue by apku04** [stlehmann/pyads#368] opened 2024-02-07 17:13 UTC
This suggests that the adslib.so library included with pyads is compiled for a 32-bit architecture, whereas my system is based on a 64-bit architecture (aarch64), leading to an incompatibility issue. 

`SError: /usr/local/lib/python3.11/dist-packages/pyads/adslib.so: wrong ELF class: ELFCLASS32`

**Expected Behavior**
it could be nice to have pyads to be compatible with 64-bit rpi Linux systems, when installing from pip isntall

**Steps to Reproduce**
Install pyads version 3.3.9 on a Raspberry Pi running a 64-bit Linux OS and Python 3.11.2.
Attempt to import pyads in a Python script or interactive session.
The import fails with the aforementioned OSError.

**Possible Solutions**
pip package for 64-bit version of adslib.so for aarch64 systems.

**Work around**
To build it from source, but i am looking forward for an "off the shelf solution" if it is possible :)

**Comment by chrisbeardy** [comment] 2024-02-08 16:32
Possibly linked to #363

**Comment by chrisbeardy** [comment] 2024-02-08 16:42
also linked to #22 #36 #147 #365, closing as duplicate of #365

**Closed by chrisbeardy** 2024-02-08 16:42 UTC

**Comment by apku04** [comment] 2024-02-08 16:46
ahh great...i'll follow the other issue then ..thx :)
